### ISSUE TITLE
Redo an image

### ISSUE THREAD

**Issue by pharaone** [pixelr0/balls#10]
redo this please, it's against the style of all the other icons and other images
![image](https://cloud.githubusercontent.com/assets/17162630/14589302/f3a7984c-04de-11e6-8063-1d0288dae4ac.jpeg)

**Comment by pixelr0** [comment]
soon.. i have some designs in the working but they are not ready yet

**Comment by pixelr0** [comment]
done, update :D

**Comment by pixelr0** [comment]
btw.. can you upload some screenshot of the game, the right side looks weird

**Comment by pharaone** [comment]
Very nice!
