### ISSUE TITLE
lvl 88 bug moved to lvl 108

### ISSUE THREAD

**Issue by Mangnoppa** [pixelr0/balls#12]
Hey,

the "game freezes in lvl 88"-bug is now present in lvl 108. I have a bq E4.5 and running version 0.232 of balls.

Mangnoppa

**Comment by pixelr0** [comment]
and it;s also in 0.233. i'll fix it in the next update. thanks for reporting this bug, most of the times i'm just not aware of this type of bugs because i can't play all the levels every time i change something :D so this bug report helps a lot!  thanks!

**Comment by pixelr0** [comment]
please update, should be fixed in 0.234

**Comment by Mangnoppa** [comment]
Nice, thank you, works great. Really good and addictive game! 
If I will find a new bug I'll open a new issue.

**Comment by pixelr0** [comment]
yep, please do

thanks :D and fave fun
