### ISSUE TITLE
lvl 101 - lvl 120 Cloud is over balls

### ISSUE THREAD

**Issue by Mangnoppa** [pixelr0/balls#13]
Hey there,

as you can see in the pictures the cloud is located over the balls so you can't see them.

![screenshot20160427_075801095](https://cloud.githubusercontent.com/assets/11314222/14859841/3fb6fe70-0ca6-11e6-8b8f-491371060a55.png)
![screenshot20160427_075510655](https://cloud.githubusercontent.com/assets/11314222/14859840/3fb6d382-0ca6-11e6-8898-330ac7cab399.png)

**Comment by pixelr0** [comment]
right :D will fix in the next update. thanks for reporting bugs o/

**Comment by pixelr0** [comment]
fixed in 0.239

**Comment by Mangnoppa** [comment]
Works, thank you

**Comment by pixelr0** [comment]
yay! thank you!
