### ISSUE TITLE
Picture of new stage is not loading, need to reboot balls

### ISSUE THREAD

**Issue by Mangnoppa** [pixelr0/balls#14]
Hey there,

one more bug I noticed over a couple of versions now. As you can see in the picture below, the logos of the new stages are not loading unless you reboot balls.

![screenshot20160427_172606950](https://cloud.githubusercontent.com/assets/11314222/14859935/9cbda150-0ca6-11e6-8f9b-5b0e34962b0d.png)

**Comment by pixelr0** [comment]
should be fixed now v0.237+ also added a message when the new world gets unlocked

**Comment by pixelr0** [comment]
update and try it :D

**Comment by Mangnoppa** [comment]
Okay thank you, works like a charm. Is there a chance to unlock stages or lvls without playing them all from the beginning?

**Comment by pixelr0** [comment]
awesome idea but i think it's a bit late for balls, i have to rewrite some things to make it work in this way. but yep GOOD idea and there will also be balls 2 :P and other games

**Comment by Mangnoppa** [comment]
Really glad, you plan balls 2 and other games as well.
