### ISSUE TITLE
game progress is not saved

### ISSUE THREAD

**Issue by pixelr0** [pixelr0/balls#3]
from reviews it seems that "game progress is not saved" on some phones o_O

https://uappexplorer.com/app/balls.briketa

tracking bug

**Comment by pixelr0** [comment]
bug fixed in v65 please try 

bug reported here https://bugs.launchpad.net/canonical-devices-system-image/+bug/1551365

**Comment by SanderKlootwijk** [comment]
Saving works now :P

**Comment by pixelr0** [comment]
ok then :D closing the issue
