### ISSUE TITLE
Map button doesn't work properly

### ISSUE THREAD

**Issue by sergiqp** [pixelr0/balls#7]
Device: bq Aquaris E4.5 Ubuntu Edition | Ubuntu release: 15.04 (r298)

When the map inside a game (https://cloud.githubusercontent.com/assets/14638571/14160685/413fe7ee-f6de-11e5-904a-89e4f9691878.jpg) is pressed by a mouse pointer it doesn't do anything. But when it is pressed by a finger it takes you to the previous screen (https://cloud.githubusercontent.com/assets/14638571/14160686/41475024-f6de-11e5-8337-ada0abea3724.jpg).

The map on the levels screen (https://cloud.githubusercontent.com/assets/14638571/14160686/41475024-f6de-11e5-8337-ada0abea3724.jpg) works properly by both methods.

Thanks for your awesome game!

**Comment by pixelr0** [comment]
update and try again :D should be fixed in 0.161

**Comment by sergiqp** [comment]
Yes, now it works. Thanks. :))

**Comment by pixelr0** [comment]
yay! :dancer:
