### ISSUE TITLE
Map not viewed in level screen

### ISSUE THREAD

**Issue by sergiqp** [pixelr0/balls#8]
As you can see, the map to go back to the main screen is not viewed after the screen has fade to dark, although I can press on it. :-)

![screenshot](https://cloud.githubusercontent.com/assets/14638571/14494105/6f6740a8-0189-11e6-8b51-9f3681413f3b.jpeg)

**Comment by pixelr0** [comment]
oops this is not good :D  the background shouldn't be black 
investigating :P

**Comment by sergiqp** [comment]
Sorry, I forgot to say I'm in rc proposed. Try in stable.

**Comment by pixelr0** [comment]
it shouldn't matter, i think... i'm also on rc proposed btw (meizu mx4). you have a nexus4, right?

**Comment by pixelr0** [comment]
sorry  bq Aquaris E4.5 :D

**Comment by pixelr0** [comment]
just pushed a new update, can you please update to 0.202?

**Comment by sergiqp** [comment]
Fixed! Thanks.

![screenshot2](https://cloud.githubusercontent.com/assets/14638571/14530166/fcb97d1c-0257-11e6-83ff-954ec12d0189.jpeg)

And yes, I have an E4.5 with last rc-proposed update (r313).

Go ahead with your amazing game! :)

**Comment by pixelr0** [comment]
yay! Thanks for reporting bugs :P

**Comment by sergiqp** [comment]
:-))
