### ISSUE TITLE
Nexus4 graphic problem

### ISSUE THREAD

**Issue by sistemx** [pixelr0/balls#9]
Hello, I am beginer and I firstly highlight bug by this way. So I hope I am doing every correctly. So On nexus 4 last update(0.201) happen graphic problem, you can see on attached photo.

**Comment by pixelr0** [comment]
i think you forgot to attach the photo? :D 
i can't find it, btw do you know if the graphic problem started with 0.201 or it was present even before?

**Comment by pixelr0** [comment]
just pushed a new update, can you please update to 0.202?

**Comment by sistemx** [comment]
After update, it works fine now. Thanks :)

**Comment by pixelr0** [comment]
yay :D THANKS for reporting the bug!
